services:
  web:
    image: php:8.4-rc-apache
    container_name: apache_web
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WEB_ROOT: ${WEB_ROOT}


  db:
    image: mysql:latest
    restart: always
    build:
     context: ./db/
    environment:
      MYSQL_DATABASE: travel_data
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/var/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    depends_on:
      - db

volumes:
  db_data: