services:
  web:
    container_name: travel_web
    build:
      context: web/
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: no
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WEB_ROOT: ${WEB_ROOT}
    volumes:
      - ./web:/var/www/html/
    depends_on:
      - db


  db:
    restart: no
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - travel_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  travel_data: